---
title: "Experience"
output: 
  html_document:
    css: bootstrap.css
    theme: cosmo
---
Here's a brief introduction of my academic and professioncal experience.

## *Education*
I received a bachelor degree in Biological Science from Xiamen University, School of life science in June, 2022. Now I am a first-year MS student of biostatistics in Columbia University Mailman School of Public Health.

## *Research Experiences*
During my sophomore year, I joined Dr. Li Qinxi’s laboratory because of my interest in tumor metabolism and participated in numerous projects. I applied content from my bioinformatics courses by obtaining gene X from a mouse cDNA library and ensuring the gene was successfully inserted using genetic sequencing. I also participated in another project that explored the way a protein (i.e., c-Src) related to tumorigenesis. I analyzed the G6PD expression of human colon cancer samples statistically, using unpaired Student’s t test. I also performed a correlation between phosphor-G6PD and phosphor-Src with Pearson’s r test. Our research group made significant discoveries that were published in Oncogene.

To learn more about biostatistics methods, in 2020, I enrolled in an internship project of University of Cambridge. I chose Artificial Intelligence and Computational Biology Models for Health as my research project. With the guidance of Dr. Pietro Lio’, I selected Convolutional Neural Networks (CNN) as an algorithm and constructed it with TensorFlow in Python. I used logistic regression to classify the CT images of the patients and other information of them. I trained the model to fit the dataset and verified it on the test data. Ultimately, I successfully completed the project and improved my practical programming skills. This experience further aroused my interest in biostatistics.

From the autumn of 2021, I have been participating in in the biostatistical program of Dr. CHEN Tianmu. In order to figure out how different circumstances and different epidemic preventing strategies will influence the susceptibility of humans and animals respectively, I have established a stimulating model for SARS-CoV-2 as a zoonosis based on SEAIR model using Berkeley Madonna. From this experience, not only have I acquired abundant knowledge about the dynamic models in epidemiology, but also developed the capability of model fitting and data visualization. 

## *Publication*
Ma H, Zhang F, Zhou L, Cao T, Sun D, Wen S, Zhu J, Xiong Z, Tsau M-T, Cheng M-L, Hung L-M,
Zhou Y, Li Q*. c-Src facilitates tumorigenesis by phosphorylating and activating G6PD. Oncogene 2021 March 08; 40:2567–2580
