---
title: "Instacart_Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)

data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### The number of orders under different departments.

```{r}
instacart %>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) %>%
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### The relationship between the days since the last order and the number of goods the customers buy.

```{r}
instacart %>%
  group_by(order_id, days_since_prior_order) %>%
  summarize(n_obs = n()) %>%
  plot_ly(
    x = ~days_since_prior_order, y = ~n_obs, type = "box")
```

### Trend of the number of orders in a day across hours

```{r}
instacart %>%
  group_by(order_hour_of_day) %>%
  summarize(n_obs = n()) %>%
  plot_ly(
    x = ~order_hour_of_day, y = ~n_obs, type = "scatter", mode = "lines+markers"
  )
```

