---
title: "NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
library(ggridges)
```

```{r, include = FALSE}
data("ny_noaa")

ny_noaa_tidy = 
ny_noaa %>%
  janitor::clean_names() %>%
  separate(col = date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = as.integer(month)) %>%
  mutate(year = as.integer(year)) %>%
  mutate(day = as.integer(day)) %>%
  mutate(tmax = as.integer(tmax)/10) %>%
  mutate(tmin = as.integer(tmin)/10)
```


Column {data-width=650}
-----------------------------------------------------------------------

### tmax vs tmin for the full dataset

```{r}
ny_noaa_tidy %>%
  select(tmax, tmin) %>%
  na.omit() %>%
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temperature") %>%
  ggplot(aes(x = temperature, y = observation)) +
  geom_density_ridges(scale = .85) +
  viridis::scale_fill_viridis(discrete = TRUE) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### the average max temperature in January across the years

```{r}
mean_tmax = 
  ny_noaa_tidy %>%
  filter(month == 1) %>%
  select(id, year, month, tmax) %>%
  group_by(id, year, month) %>%
  summarize(average_tmax = mean(tmax, na.rm = TRUE)) 

mean_tmax %>%
  na.omit() %>%
  ggplot(aes(x = year, y = average_tmax, group = id)) +
  geom_line() +
  labs(x = "year",
    y = "average max temperature"
  )
```

### Chart C

```{r}

```

